[project]
name = "token-swap"
description = "Automated Market Maker for decentralized token swaps"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
[contracts.token-swap]
path = "contracts/token-swap.clar"
clarity_version = 2
epoch = 2.4
